name: 'Setup Ant1.9'
description: 'Install Ant'
inputs:
  path-ant:
    description: 'Path  of Ant'
    required: true
    default: '/'
runs:
  using: 'composite'
  steps:
    - name: Imprimiendo path
      run: |
        echo ${{ inputs.path-ant}} 
      shell: bash

    - name: Install Ant
      run: | # Install Ant, specifict version that supports Java 5
        sudo apt remove ant -y
        sudo mkdir /opt/ant
        sudo tar -xvf ${{ inputs.path-ant}}  -C /opt/ant
        sudo update-alternatives --install "/usr/bin/ant" "ant" "/opt/ant/apache-ant-1.7.1/bin/ant" 1
        sudo update-alternatives --set ant /opt/ant/apache-ant-1.7.1/bin/ant
        export ANT_HOME=/opt/ant/apache-ant-1.7.1
        echo $PATH
        export PATH=$ANT_HOME/bin:$PATH
        echo "PATH changed"
        echo $PATH
      shell: bash